config/routes.rb
Rails.application.routes.draw do
 root "sessions#new"

 get '/login' => 'sessions#new'

 post '/login' => 'sessions#create'

 delete '/logout' => 'sessions#destroy'

 resources :cities do
  resources :posts
 end

 # get 'cities/new'

 # get 'cities/edit'

 # get 'cities/index'

 # get 'cities/:id', to: 'cities#show', as: 'city'

 resources :users

 # post '/users', to: 'users#create'

 # get 'users/new', to: 'users#new', as: 'new_user'

 # get 'users/edit'

 # get 'users/show'



 resources :users, only: [] do
   resources :posts, only: [:edit, :index, :show]
 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	validates :name, presence: true, length: {minimum: 1, maximum: 200}
	validates :content, presence: true
	belongs_to :user
	belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
  belongs_to :city

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
       if !session[:current_user]
           flash[:error] = "You need to be logged in"
           redirect_to "/login"
       end
   end

   def current_user
     if session[:current_user] != nil
       return User.find(session[:current_user]["id"])
     else
       false
     end
   end

  def require_login
    unless current_user
      #send an http response to stop program execution
      redirect_to root_path
    end
  end

  def owned_by?(user)
    return user == current_user
  end

  def owner_check(user)
    unless owned_by?(user)
      redirect_to root_path
    end
  end

   helper_method :current_user
   helper_method :owned_by?
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
  	@city = City.new
  end

  def edit
  end

  def index
  	@cities = City.all
  end

  def show
  	@city = City.find_by_id(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: :new
  def new
    @post = Post.new
    @city = City.find(params[:city_id])
  end

  def edit
    @post = Post.find(params[:id])
    @city = City.find(params[:city_id])
  end

  def update
    p 'xxxxx'
    Post.find(params[:id]).update(post_params)
    @city = City.find(params[:city_id])

    redirect_to city_path(@city)

  end

  def create
    # associate post with a city
    post = City.find(params[:city_id]).posts.new(post_params)
    post.user_id = current_user.id
    post.save

    city = City.find(params[:city_id])
    redirect_to city_path(city)
  end

  def index
    @posts = User.find(current_user.id).posts
  end

  def show
    post_id = params[:id]
    @post = Post.find_by_id(post_id)
  end

  def destroy
    post = Post.find(params[:id])
    city = post.city.id
    post.destroy


    redirect_to city_path(city)
  end

  private

    def post_params
      params.require(:post).permit(:user_id, :city_id, :name, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #Step 1: Query DB for user based on email
    #Step 2: If email is not found redirect back to login with an error flash message
    #Step 3: If email is found then authenticate the password
    #Step 4: Redirect to book list

    user = User.find_by(email: params[:email])

    if user
        current_user = user.authenticate(params[:password])

        if current_user
            #Authenticated! Yay!
            session[:current_user] = current_user
            redirect_to user_path(user.id)
        else
            flash[:error] = "Incorrect password"
            redirect_to :back
        end
    else
        flash[:error] = "Email was not found"
        redirect_to :back
    end

end

def destroy
  session[:current_user] = nil
  current_user = nil
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @cities = City.all
  end

  def create
    @user = User.new(user_params)
    @user.city_id = params[:city][:city_id]
    @user.save

    if @user.valid?
        flash[:success] = "Thanks! Please log in."
        redirect_to "/login"
    else
        flash[:error] = "Something went wrong."
        redirect_to login_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.city_id = params[:city][:city_id]
    @user.update(user_params)
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    city_id = @user.city.id
    @city = City.find(city_id)
    @posts = @user.posts
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :city_id, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities</h1>
<% @cities.each do |city| %>
	<div class="row">
	  <div class="col s12 m7">
	    <div class="card">
	      <div class="card-image">
	        <img src="<%= city.image_url %>">
	      </div>
	      <div class="card-content">
					<p class="card-title"><%= link_to city.name, city_path(city) %></p>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h1><%= @city.name %></h1>

<a ></a>
<i class="material-icons"><%= link_to "New Post", new_city_post_path(@city.id), method: "get", class: "waves-effect waves-light btn" %> <br> <br>
<div class="city-img">
	<%= image_tag(@city.image_url) %>
</div>
<br><br>
<div class="container">
  <div class="row">
    <% @city.posts.in_groups_of(2, false) do |post_groups|  %>
    <div class="row">
			<% post_groups.each do |post| %>
      <div class="col s6 m5">
				<div class="chip">
		      <img src="<%= post.user.image_url %>" alt="Contact Person"><%= post.user.email %>
		    </div>
        <div class="card-panel teal">
          <span class="white-text">
            <%= link_to post.name, user_post_path(post.user_id, post) %>
            <p><%= post.content%></p>
						<% if owned_by?(post.user) %>
              <%= link_to "Edit", edit_city_post_path(@city.id, post.id), method: :get %> |
              <%= link_to "Delete", city_post_path(@city.id, post.id), method: :delete %>
            <% end %>
          </span>
        </div>
      </div>
			<% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  	<!-- Optional theme -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_error_flash.html.erb
<% if flash[:error] %>
    <div class="container small-container">
        <div class="alert alert-danger">
            <%= flash[:error] %>
        </div>
    </div>
<% end %>

app/views/partials/_login_form.html.erb
<div class="row">
    <form class="col s12">


      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>


    </form>
  </div>

app/views/partials/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">VagaBond</i></a>
    <ul class="right">
      <% if current_user != false %>
        <li>Welcome: <%= current_user.email %></li>
        <li><%= link_to 'Profile', user_path(current_user.id) %></li>
        <li><%= link_to 'cities', cities_path %></li>
        <li><%= link_to 'log out', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'log in', login_path %></li>
        <li><%= link_to 'sign up', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_sign_up_form.html.erb
<div class="row">

    <%= form_for @user do |f| %>

      <div class="row">
        <div class="input-field col s12">
            <%= select("city", "city_id", City.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select City'}) %>

          </div>
      </div>
      <!-- how are we going to get the cities to display so that the user can select one by name -->


      <div class="row">
        <div class="input-field col s12">
            <%= f.text_field :image_url %>
          <label for="city_id">Image Url</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
            <%= f.email_field :email %>
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
            <%= f.password_field :password %>
          <label for="password">Password</label>
        </div>
      </div>

        <%= f.submit "Submit" %>



      <% end %>
  </div>

app/views/partials/_success_flash.html.erb
<% if flash[:success] %>
    <div class="container small-container">
        <div class="alert alert-success">
            <%= flash[:success] %>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<div class="row">
  <%= form_for [@city, @post], method: "put" do |f| %>
    </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <label for="name">Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :content %>
          <label for="content">Content</label>
        </div>
      </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<br><br><br>
<div class="container">
  <div class="row">
    <% unless @posts.length > 0 %>
      <p> Make some posts! </p>
    <% end %>
    <% @posts.each do |post| %>
    <div class="chip">
      <img src="<%= post.user.image_url %>" alt="Contact Person"><%= post.user.email %>
    </div>
    <div class="row">
      <div class="col s12 m5">
        <div class="card-panel light-grey">
          <span class="white-text">
            <%= link_to post.name, user_post_path(post.user_id, post) %>
            <p><%= post.content%></p>
            <%= link_to "Edit", edit_city_post_path(post.city.id, post.id), method: :get %> |	
 					  <%= link_to "Delete", city_post_path(post.city.id, post.id), method: :delete %>
          </span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h2>Create a new post</h2>

<div class="row">
    <%= form_for [@city, @post], method: "post" do |f| %>
      </div>
      <div class="row">
        <div class="input-field col s12">
            <%= f.text_field :name %>
          <label for="name">Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
            <%= f.text_field :content %>
          <label for="content">Content</label>
        </div>
      </div>
        <%= f.submit "Submit" %>
      <% end %>
  </div>

app/views/posts/show.html.erb
<h3><%= @post.name%></h3>
<h5><%= @post.user.email%></h5>
<p><%= @post.content%></p>

app/views/users/edit.html.erb
<h2>Edit your profile</h2>
<% if owned_by?(@user) %>
	<%= render 'partials/sign_up_form' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>



	<%= render 'partials/sign_up_form' %>

app/views/users/show.html.erb
<h5><%= @user.email %> profile page</h5>
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <img src="<%= @user.image_url %>">
      </div>
      <div class="card-content">
        <p class="card-title"><strong>Email:</strong> <%= @user.email %></p>
        <p class="card-title"><strong>Join Date:</strong> <%= @user.created_at.strftime("%B" + " " + "%d" + ", " + "%Y") %></p>
        <p class="card-title"><strong>Current City:</strong> <%= link_to @user.city.name, city_path(@city) %></p>
        <% if owned_by?(@user) %>
          <%= link_to 'EDIT PROFILE', edit_user_path, method: "get" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br><br><br>
<div class="container">
  <h5>Posts</h5>
</div>

<div class="container">
  <div class="row">
    <% @posts.in_groups_of(2, false) do |post_groups|  %>
    <div class="row">
			<% post_groups.each do |post| %>
      <div class="col s6 m5">
				<div class="chip">
		      <img src="<%= post.user.image_url %>" alt="Contact Person"><%= post.user.email %>
		    </div>
        <div class="card-panel teal">
          <span class="white-text">
            <%= link_to post.name, user_post_path(post.user_id, post) %>
            <p><%= post.content%></p>
						<% if owned_by?(@user) %>
              <%= link_to "Edit", edit_city_post_path(@city.id, post.id), method: :get %> |
              <%= link_to "Delete", city_post_path(post.id), method: :delete %>
            <% end %>
          </span>
        </div>
      </div>
			<% end %>
    </div>
    <% end %>
  </div>
</div>